spring.application.name=shopdienthoaiAPI
# ===================================================
# 1. C?U HÌNH SERVER
# ===================================================
server.port=8081

# ===================================================
# 2. C?U HÌNH K?T N?I POSTGRESQL (DATASOURCE)
# ===================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ShopBanHang
spring.datasource.username=postgres
# Thay mat_khau_cua_ban bang mat khau ban da nhap tren pgAdmin
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================
# 3. C?U HÌNH JPA & HIBERNATE
# ===================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'validate': Chi doi chieu Entity voi database hien tai, khong tu y xoa hoac sua bang
spring.jpa.hibernate.ddl-auto=none

# In cau lenh SQL ra console khi he thong chay
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Giu nguyen ten bang va ten cot theo dung khai bao trong Entity (khong tu dong doi sang chu thuong)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

